using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WardenCore.Models
{


    public class DeckViewModel
    {
        public DeckViewModel()
        {
            this.ObjectStates = new _objectStates[2];
            this.ObjectStates[0] = new _objectStates();
            this.ObjectStates[1] = new _objectStates();
        }

        public string SaveName { get { return string.Empty; } }
        public string GameMode { get { return string.Empty; } }
        public double Gravity { get { return 0.5; } }
        public double PlayArea { get { return 0.5; } }
        public string Date { get { return string.Empty; } }
        public string Table { get { return string.Empty; } }
        public string Sky { get { return string.Empty; } }
        public string Note { get { return string.Empty; } }
        public string Rules { get { return string.Empty; } }
        public string XmlUI { get { return string.Empty; } }
        public string LuaScript { get { return string.Empty; } }
        public string LuaScriptState { get { return string.Empty; } }

        public _objectStates[] ObjectStates { get; set; }

        public string[] TabStates { get; set; }
        public string VersionNumber { get { return string.Empty; } }



    }

    public class _objectStates
    {
        public _objectStates()
        {
            this.Transform = new _transformForDeck();
            this.ColorDiffuse = new _color();
            this.CustomDeck = new Dictionary<string, _customCard>();
            this.ContainedObject = new List<_containedObject>();

        }

        public string Name { get { return "Deck"; } }
        public _transformForDeck Transform;
        
        public string Nickname { get { return string.Empty; } }
        public string Description { get { return "generated by Warden"; } }
        public _color ColorDiffuse;
        public bool Locked { get { return false; } }
        public bool Grid { get { return true; } }
        public bool Snap { get { return true; } }
        public bool IgnoreFoW { get { return false; } }
        public bool Autoraise { get { return true; } }
        public bool Sticky { get { return true; } }
        public bool Tooltip { get { return true; } }
        public bool GridProjection { get { return false; } }
        public bool HideWhenFaceDown { get { return true; } }
        public bool Hands { get { return false; } } 
        public bool SidewaysCard { get { return false; } }


        public int[] DeckIDs { get; set; } /* carte inserite */
        public Dictionary<string,_customCard> CustomDeck { get; set; } /* carta al top */

        public List<_containedObject> ContainedObject { get; set; }

        public string XmlUI { get { return string.Empty; } }
        public string GUID { get { return string.Empty; } }
        public string LuaScript { get { return string.Empty; } }
        public string LuaScriptState { get { return string.Empty; } }



    }

    public class _transformForDeck
    {
       public double posX { get { return 6.19986153; } }   
       public double posY { get { return 1.04492879; } }
       public double posZ { get { return -5.182258; } }
       public double rotX { get { return 3.51414456E-05; } }
       public double rotY { get { return 180.011719; } }
       public double rotZ { get { return 180.0; } }
       public double scaleX { get { return 1.0; } }
       public double scaleY { get { return 1.0; } }
       public double scaleZ { get { return 1.0; } }
    }

    public class _transformForCard
    {
        public double posX { get { return 0.152652532; } }
        public double posY { get { return 1.17950535; } }
        public double posZ { get { return 0.05491744; } }
        public double rotX { get { return -0.005726053; } }
        public double rotY { get { return 179.983; } }
        public double rotZ { get { return 180.035568; } }
        public double scaleX { get { return 1.0; } }
        public double scaleY { get { return 1.0; } }
        public double scaleZ { get { return 1.0; } }
    }

    public class _color
    {
        public double r { get { return 0.713235259; } }
        public double g { get { return 0.713235259; } }
        public double b { get { return 0.713235259; } }

    }

    public class _customCard
    {
        public string FaceURL { get; set; }
        public string BackURL { get; set; }
        public int NumWidth { get { return 1;  } }
        public int NumHeight { get { return 1; } }
        public bool BackIsHidden { get { return true; } }
        public bool UniqueBack { get { return true; } }

    }

    public class _containedObject 
    {
        public _containedObject()
        {
            this.Transform = new _transformForCard();
            this.ColorDiffuse = new _color();
        }
        public string Name { get { return "Card"; } }
        public _transformForCard Transform;
        public string Nickname;
        public string Description { get { return "generated by Warden"; } }
        public _color ColorDiffuse;
        public bool Locked { get { return false; } }
        public bool Grid { get { return true; } }
        public bool Snap { get { return true; } }
        public bool IgnoreFoW { get { return false; } }
        public bool Autoraise { get { return true; } }
        public bool Sticky { get { return true; } }
        public bool Tooltip { get { return true; } }
        public bool GridProjection { get { return false; } }
        public bool HideWhenFaceDown { get { return true; } }
        public bool Hands { get { return true; } } 
        public bool SidewaysCard { get { return false; } }
        public int CardID { get; set; }


        public Dictionary<string, _customCard> CustomDeck { get; set; } 


        public string XmlUI { get { return string.Empty; } }
        public string LuaScript { get { return string.Empty; } }
        public string LuaScriptState { get { return string.Empty; } }

        public string GUID { get; set; } /* da capire */



    }

}